import os
import datetime
from crewai import Agent, Task, Crew
from langchain_openai import ChatOpenAI

# --- Setup Local AI ---
os.environ["OPENAI_API_BASE"] = "http://localhost:11434/v1"
os.environ["OPENAI_BASE_URL"] = "http://localhost:11434/v1"
os.environ["OPENAI_API_KEY"] = "NA"

llm = ChatOpenAI(model="llama3-70b-8192")
def save_code(task_name, code_content):
    folder = "Deliverables/Tech"
    if not os.path.exists(folder): os.makedirs(folder)
    
    timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{folder}/Code_{timestamp}.py"  # Default to Python file
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"# Task: {task_name}\n# Generated by Mission Control Tech Squad\n\n")
        f.write(code_content)
    return filename

def run_tech_crew(task_description):
    print(f"\n💻 STARTING TECH CREW: {task_description}\n")

    # 1. Agents
    architect = Agent(
        role='Senior Solutions Architect',
        goal='Design efficient code structures',
        backstory='You are a veteran coder who writes clean, scalable code.',
        allow_delegation=False,
        llm=llm
    )
    
    developer = Agent(
        role='Lead Python Developer',
        goal='Write bug-free code quickly',
        backstory='You type faster than you think. You build functional prototypes in minutes.',
        allow_delegation=False,
        llm=llm
    )

    # 2. Tasks
    plan_task = Task(
        description=f"Analyze this request: '{task_description}'. Create a step-by-step coding plan.",
        agent=architect,
        expected_output="A list of functions and logic needed."
    )

    code_task = Task(
        description="Write the COMPLETE executable code based on the plan. No placeholders.",
        agent=developer,
        expected_output="Final Python/HTML code block."
    )

    # 3. Execution
    crew = Crew(agents=[architect, developer], tasks=[plan_task, code_task], verbose=True)
    result = crew.kickoff()
    
    # 4. Save
    saved_path = save_code(task_description, str(result))
    return f"💻 TECH SQUAD REPORT:\nCode generated successfully.\n📂 Saved at: {saved_path}"